version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bibliotheque_web
      MYSQL_USER: test_users
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build: ./backend-gestion-biblio
    env_file:
      - ./backend-gestion-biblio/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
