# Railway Deployment Configuration
version: 1

services:
  # Backend API
  backend:
    source: backend-gestion-biblio
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5000
    variables:
      DB_HOST: ${{ railway.db.host }}
      DB_PORT: ${{ railway.db.port }}
      DB_NAME: ${{ railway.db.name }}
      DB_USER: ${{ railway.db.user }}
      DB_PASSWORD: ${{ railway.db.password }}
      JWT_SECRET: ${{ railway.backend.JWT_SECRET }}
      EMAIL_USER: ${{ railway.backend.EMAIL_USER }}
      EMAIL_PASS: ${{ railway.backend.EMAIL_PASS }}
      EMAIL_SERVICE: ${{ railway.backend.EMAIL_SERVICE }}
      FRONTEND_URL: ${{ railway.frontend.url }}

  # Frontend
  frontend:
    source: frontend-gestion-biblio
    build:
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=${{ railway.backend.url }}

  # Database MySQL
  database:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: ${{ railway.db.root_password }}
      MYSQL_DATABASE: ${{ railway.db.name }}
      MYSQL_USER: ${{ railway.db.user }}
      MYSQL_PASSWORD: ${{ railway.db.password }}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema_complet.sql:/docker-entrypoint-initdb.d/schema_complet.sql

volumes:
  mysql_data:
